{{- /*
GKE Google Secret Manager (GSM) integration.

This resource is optional and only rendered when:
- .Values.gsm.enabled is true
- .Values.gsm.secretsync.enabled is true
- The SecretSync CRD is available on the cluster

NOTE: By default, this template uses the SecretSync resource name as the name
of the Kubernetes Secret that gets created. The default is set to match
.Values.config.secret so the chart's existing secret wiring continues to work.
*/ -}}
{{- if and .Values.gsm.enabled (.Values.gsm.secretsync.enabled) (.Capabilities.APIVersions.Has "secret-sync.gke.io/v1/SecretSync") -}}
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: {{ default .Values.config.secret .Values.gsm.secretsync.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "bindplane.name" . }}
    app.kubernetes.io/stack: bindplane
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceAccountName: {{ include "bindplane.fullname" . }}
  secretProviderClassName: {{ default (printf "%s-gsm" (include "bindplane.fullname" .)) .Values.gsm.spc.name }}
  secretObject:
    type: {{ .Values.gsm.secretsync.secretObject.type }}
    {{- if .Values.gsm.secretsync.secretObject.data }}
    data:
{{- toYaml .Values.gsm.secretsync.secretObject.data | nindent 6 }}
    {{- else }}
    data: []
    {{- end }}
{{- end }}

