{{- /*
GKE Google Secret Manager (GSM) integration.

This resource is optional and only rendered when:
- .Values.gsm.enabled is true
- The SecretProviderClass CRD is available on the cluster
*/ -}}
{{- if and .Values.gsm.enabled (.Capabilities.APIVersions.Has "secrets-store.csi.x-k8s.io/v1/SecretProviderClass") -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ default (printf "%s-gsm" (include "bindplane.fullname" .)) .Values.gsm.spc.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "bindplane.name" . }}
    app.kubernetes.io/stack: bindplane
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  provider: gke
  parameters:
    secrets: |
      {{- range .Values.gsm.spc.secrets }}
      - resourceName: "projects/{{ $.Values.gsm.projectId }}/secrets/{{ .secretName }}/versions/latest"
        path: "{{ .path }}"
      {{- end }}
{{- end }}

